// Each new term in the Fibonacci sequence is generated by adding the previous 
// two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed
// four million, find the sum of the even-valued terms.

#include <stdio.h>

int fibo(int a, int b);

int main(int argc, const char * argv[]) {
  int firstprev = 1, secondprev = 1, current, sum = 0;

  while(sum < 4000000) {
    current = fibo(firstprev, secondprev);
    sum += (current % 2 == 0) ? current : 0;
    secondprev = firstprev;
    firstprev = current;
  }
  printf("sum = %d.\n", sum);
  return 0;
}

int fibo(int a, int b) {
  return a + b;
}
