// Each new term in the Fibonacci sequence is generated by adding the previous 
// two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed
// four million, find the sum of the even-valued terms.

#include <stdio.h>

int main(int argc, const char * argv[]) {
  int fib1 = 1, fib2 = 1, current, sum = 0;

  while(sum < 4000000) {
    current = fib1 + fib2;
    sum += (current % 2 == 0) ? current : 0;
    fib2 = fib1;
    fib1 = current;
  }
  printf("sum = %d.\n", sum);
  return 0;
}

