// The sequence of triangle numbers is generated by adding the natural numbers.
// So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first
// ten terms would be:
//
// 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
//
// Let us list the factors of the first seven triangle numbers:
//
//     1: 1
//     3: 1,3
//     6: 1,2,3,6
//    10: 1,2,5,10
//    15: 1,3,5,15
//    21: 1,3,7,21
//    28: 1,2,4,7,14,28
//    We can see that 28 is the first triangle number to have over five
//    divisors.
//
//    What is the value of the first triangle number to have over five hundred
//    divisors?

#include <math.h>
#include <stdio.h>

int divisors(int nb)
{
  int count = 0, max = sqrt(nb), i = 1;

  for (i = 1; i < max; i++)
    if (nb % i == 0)
      count += 2;
  if (max * max == nb)
    count++;
  return (count);
}

int main()
{
  int nb = 0, i = 0;

  for (i = 1; ; i++)
  {
    nb += i;
    if (divisors(nb) > 500)
    {
      printf("%d\n", nb);
      break;
    }
  }
  return (0);
}
